name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: agodio/itba-so:1.0
    steps:
    - uses: actions/checkout@v2
    - name: build toolchain
      run: cd Toolchain; make
    - name: build
      run: make all
